### ISSUE TITLE
Building for docker is already in the TDS_FDW repo

### ISSUE THREAD

**Issue by SudoerWithAnOpinion** [huggla/tds_fdw#1]
It appears your instructions already exist in the official TDS_FDW repo under the InstallAlpine.md file.
However, you seem to imporve on these instructions.

I'd recommend forking TDS_FDW from either GeoffMontee or mine from https://github.com/TheRevenantStar/tds_fdw and updating the directions, we'll make sure a pull request gets reviewed if you want to submit one!

**Comment by huggla** [comment]
This is the dockerfile for my Docker image, published on [Docker Hub](https://hub.docker.com/r/huggla/tds_fdw/). It isn't intended to be instructions.
